### ISSUE TITLE
Extend location models with specific type Flood

### ISSUE THREAD

**Issue by JeppeMariagerLam** [PIN-Cambodia/Sensor-Management-System#11]
If a location is marked with type Flood:

- Properties: Sensor height (int), watch level (int), warning level (int) and severe warning level (int)
- Methods: transformDataPoint (when the data point comes in from the sensor, we get the distance from the sensor to the water. But we need to store the water height in the data point, so this method needs to data in all the values from the submitted sensor data, and add an additional field that is called waterHeight, calculated as: Sensor height (from location) - distance reported from the sensor)

**Comment by sopheakyong** [comment]
- properies  Sensor height (int), watch level (int), warning level (int) and severe warning level (int)
have been add to table location.
- waterHeight, Sensor height and distance report fields have been add to table datapoint
