### ISSUE TITLE
Extend sensor model for River sensor type

### ISSUE THREAD

**Issue by JeppeMariagerLam** [PIN-Cambodia/Sensor-Management-System#13]
If the sensor type is River, add the following:

- Properties: Sim card number (varchar255), firmware version (varchar255), hardware version (varchar255), hardware description (10 lines text), last boot (datetime)

All need to be nullable.

**Comment by JeppeMariagerLam** [comment]
Example of sim card number: 8985506081897925841

**Comment by JeppeMariagerLam** [comment]
We will also need IMEI, example: 862877034386449

**Comment by sopheakyong** [comment]
the field have been add to sensor
