### ISSUE TITLE
Location admin interface update

### ISSUE THREAD

**Issue by JeppeMariagerLam** [PIN-Cambodia/Sensor-Management-System#20]
- Rename 'Water' type to 'River'
- Remove "sensors" (should actually be called 'sensor' since there is only one)
- Rename 'Sensor Height' to 'Sensor installation height'.
- Add a help text (if possible) to sensor installation height: "Distance from riverbed to to sensor in mm"
- Add help test to Watch Level: "Distance in mm from riverbed to water level to trigger 'Watch' status"
- Add help test to Warning Level: "Distance in mm from riverbed to water level to trigger 'Warning' status"
- Add help test to Severe Warning Level: "Distance in mm from riverbed to water level to trigger 'Severe Warning' status"
- Rename 'Plan' option in status to be 'Planned'

- Add a Public comment field in both English and Khmer. We will use to this to put things like "Planned installation during May 2019" etc.

**Comment by JeppeMariagerLam** [comment]
It needs to be possible to save a new location without selecting a sensor

**Comment by chendaLoeurt** [comment]
I have done with this and also commit to master.
